# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neal Cheng
email: nncheng81@gmail.com
description: Data Scientist
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nneal1213.github.io/" # the base hostname & protocol for your site
twitter_username: nneal1213
github_username:  nneal1213
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
